name: 'tweet-coutdown'
on:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install && npm run build && npm run package
      - uses: ./
        with:
          consumer_key: ${{ secrets.TWITTER_API_KEY }}
          consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          first_message: |
            ğŸ•‘ ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³
            ğŸ“ TOEICè©¦é¨“ 2021/03/21 ã¾ã§
          target_date: '2021/03/21'
          last_message: |
            ã‚ã¨å°‘ã—é ‘å¼µã‚Šã¾ã—ã‚‡ã†ğŸ™‹ğŸ»ğŸ™‹ğŸ»â€â™€ï¸
            â€»æ¯æ—¥ 7:30 ã«æ›´æ–°(Github Actionsã‚ˆã‚Š)
            #TOEIC
            #ã‚«ã‚¦ãƒ³ãƒˆãƒ€ã‚¦ãƒ³
            #å‹‰å¼·
